# Generated by Django 4.2.4 on 2023-11-27 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('unread', models.BooleanField(db_index=True, default=True)),
                ('text', models.TextField()),
                ('rawmsg', models.TextField(null=True)),
                ('outgoing_msgid', models.CharField(max_length=250, null=True)),
                ('incoming_msgid', models.CharField(max_length=250, null=True)),
                ('smtp_delivery_state', models.CharField(choices=[('new', 'new'), ('started', 'started'), ('success', 'success'), ('failure', 'failure')], db_index=True, default='new', max_length=7)),
                ('creator', models.CharField(choices=[('human', 'human'), ('auto-self', 'auto-self'), ('auto-custom', 'auto-custom'), ('auto-generated', 'auto-generated'), ('auto-replied', 'auto-replied'), ('auto-notified', 'auto-notified')], default='human', max_length=14)),
                ('in_reply_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_replied_in', to='communication.message')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_receiver_for_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('starred_by_sender', models.BooleanField(db_index=True, default=False)),
                ('starred_by_receiver', models.BooleanField(db_index=True, default=False)),
                ('last_message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head', to='communication.message')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_threads', to=settings.AUTH_USER_MODEL)),
                ('related_thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.thread')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_threads', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submission')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.thread'),
        ),
    ]
