# Generated by Django 4.2.4 on 2023-11-24 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("documents", "0001_initial"),
        ("meetings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "documents",
                    models.ManyToManyField(
                        related_name="notifications", to="documents.document"
                    ),
                ),
                (
                    "pdf_document",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="_notification",
                        to="documents.document",
                    ),
                ),
                (
                    "submission_forms",
                    models.ManyToManyField(
                        related_name="notifications", to="core.submissionform"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "form",
                    models.CharField(
                        default="notifications.forms.NotificationForm", max_length=80
                    ),
                ),
                ("default_response", models.TextField(blank=True)),
                ("position", models.IntegerField(default=0)),
                ("includes_diff", models.BooleanField(default=False)),
                ("grants_vote_extension", models.BooleanField(default=False)),
                ("finishes_study", models.BooleanField(default=False)),
                ("is_rejectable", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CompletionReportNotification",
            fields=[
                (
                    "notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.notification",
                    ),
                ),
                ("study_started", models.BooleanField(default=True)),
                ("reason_for_not_started", models.TextField(blank=True, null=True)),
                ("recruited_subjects", models.PositiveIntegerField(null=True)),
                ("finished_subjects", models.PositiveIntegerField(null=True)),
                ("aborted_subjects", models.PositiveIntegerField(null=True)),
                ("SAE_count", models.PositiveIntegerField(default=0)),
                ("SUSAR_count", models.PositiveIntegerField(default=0)),
                ("study_aborted", models.BooleanField(default=False)),
                ("completion_date", models.DateField()),
            ],
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="ProgressReportNotification",
            fields=[
                (
                    "notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.notification",
                    ),
                ),
                ("study_started", models.BooleanField(default=True)),
                ("reason_for_not_started", models.TextField(blank=True, null=True)),
                ("recruited_subjects", models.PositiveIntegerField(null=True)),
                ("finished_subjects", models.PositiveIntegerField(null=True)),
                ("aborted_subjects", models.PositiveIntegerField(null=True)),
                ("SAE_count", models.PositiveIntegerField(default=0)),
                ("SUSAR_count", models.PositiveIntegerField(default=0)),
                ("runs_till", models.DateField(blank=True, null=True)),
            ],
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="SafetyNotification",
            fields=[
                (
                    "notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.notification",
                    ),
                ),
                (
                    "safety_type",
                    models.CharField(
                        choices=[
                            ("susar", "SUSAR"),
                            ("sae", "SAE"),
                            ("asr", "Annual Safety Report"),
                            ("other", "Other Safety Report"),
                        ],
                        db_index=True,
                        max_length=6,
                        verbose_name="Type",
                    ),
                ),
            ],
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="NotificationAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "is_final_version",
                    models.BooleanField(default=False, verbose_name="Proofread"),
                ),
                (
                    "is_rejected",
                    models.BooleanField(default=False, verbose_name="rate negative"),
                ),
                ("signed_at", models.DateTimeField(null=True)),
                ("published_at", models.DateTimeField(null=True)),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="notifications.notification",
                    ),
                ),
                (
                    "pdf_document",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="_notification_answer",
                        to="documents.document",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="notifications.notificationtype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CenterCloseNotification",
            fields=[
                (
                    "notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.notification",
                    ),
                ),
                ("close_date", models.DateField()),
                (
                    "investigator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closed_by_notification",
                        to="core.investigator",
                    ),
                ),
            ],
            bases=("notifications.notification",),
        ),
        migrations.CreateModel(
            name="AmendmentNotification",
            fields=[
                (
                    "notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.notification",
                    ),
                ),
                ("is_substantial", models.BooleanField(default=False)),
                ("needs_signature", models.BooleanField(default=False)),
                (
                    "meeting",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendments",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "new_submission_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_for_notification",
                        to="core.submissionform",
                    ),
                ),
                (
                    "old_submission_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_for_notification",
                        to="core.submissionform",
                    ),
                ),
            ],
            bases=("notifications.notification", models.Model),
        ),
    ]
