# Generated by Django 4.2.4 on 2023-12-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_notificationtype_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtype",
            name="form",
            field=models.CharField(
                default="src.notifications.forms.NotificationForm", max_length=80
            ),
        ),
    ]
