# Generated by Django 4.2.4 on 2023-11-27 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_delegatable', models.BooleanField(default=True)),
                ('is_dynamic', models.BooleanField(default=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='auth.group')),
                ('workflow_node', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.node')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(null=True)),
                ('closed_at', models.DateTimeField(db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('send_message_on_close', models.BooleanField(default=False)),
                ('reminder_message_timeout', models.DurationField(null=True)),
                ('reminder_message_sent_at', models.DateTimeField(null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('medical_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medicalcategory')),
                ('review_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasksv.task')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasksv.tasktype')),
                ('workflow_token', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='workflow.token')),
            ],
        ),
    ]
