# Generated by Django 4.2.4 on 2023-12-04 19:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("tasksv", "0002_alter_task_assigned_to_alter_task_content_type_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="task",
            managers=[
                ("unfiltered", django.db.models.manager.Manager()),
            ],
        ),
    ]
