# Generated by Django 4.2.4 on 2023-12-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasksv", "0004_alter_task_review_for"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="task",
            managers=[],
        ),
    ]
