# Generated by Django 4.2.4 on 2023-12-04 20:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("tasksv", "0005_alter_task_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="task",
            managers=[
                ("unfiltered", django.db.models.manager.Manager()),
            ],
        ),
    ]
