# Generated by Django 4.2.4 on 2023-12-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasksv", "0006_alter_task_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="task",
            managers=[],
        ),
    ]
