# Generated by Django 4.2.4 on 2023-11-24 18:25

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_filter_search", models.JSONField()),
                ("submission_filter_all", models.JSONField()),
                ("submission_filter_widget", models.JSONField()),
                ("submission_filter_widget_internal", models.JSONField()),
                ("submission_filter_mine", models.JSONField()),
                ("submission_filter_assigned", models.JSONField()),
                ("task_filter", models.TextField(null=True)),
                ("useradministration_filter", models.JSONField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ecs_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_password_change", models.DateTimeField(auto_now_add=True)),
                ("is_phantom", models.BooleanField(default=False)),
                ("is_indisposed", models.BooleanField(default=False)),
                ("is_board_member", models.BooleanField(default=False)),
                ("is_resident_member", models.BooleanField(default=False)),
                ("is_omniscient_member", models.BooleanField(default=False)),
                ("is_executive", models.BooleanField(default=False)),
                ("is_internal", models.BooleanField(default=False)),
                ("can_have_tasks", models.BooleanField(default=False)),
                ("can_have_open_tasks", models.BooleanField(default=False)),
                ("is_testuser", models.BooleanField(default=False)),
                ("session_key", models.CharField(max_length=40, null=True)),
                (
                    "gender",
                    models.CharField(choices=[("f", "Ms"), ("m", "Mr")], max_length=1),
                ),
                ("title", models.CharField(blank=True, max_length=30)),
                ("organisation", models.CharField(blank=True, max_length=180)),
                ("jobtitle", models.CharField(blank=True, max_length=130)),
                ("swift_bic", models.CharField(blank=True, max_length=11)),
                ("iban", models.CharField(blank=True, max_length=40)),
                ("address1", models.CharField(blank=True, max_length=60)),
                ("address2", models.CharField(blank=True, max_length=60)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("fax", models.CharField(blank=True, max_length=45)),
                (
                    "signing_connector",
                    models.CharField(
                        choices=[
                            ("bku", "localbku"),
                            ("onlinebku", "onlinebku"),
                            ("mobilebku", "mobilebku"),
                        ],
                        default="onlinebku",
                        max_length=9,
                    ),
                ),
                (
                    "forward_messages_after_minutes",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "task_uids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "communication_proxy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("login", "login"), ("logout", "logout")],
                        max_length=32,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(protocol="ipv4")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("is_used", models.BooleanField(db_index=True, default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ecs_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
