# Generated by Django 4.2.4 on 2023-11-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usersettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='submission_filter_all',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='submission_filter_assigned',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='submission_filter_mine',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='submission_filter_search',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='submission_filter_widget',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='submission_filter_widget_internal',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='useradministration_filter',
            field=models.JSONField(null=True),
        ),
    ]
