# Generated by Django 4.2.4 on 2023-11-24 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=25,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9._-]{1,25}$"
                            )
                        ],
                    ),
                ),
                ("color", models.IntegerField()),
                (
                    "submissions",
                    models.ManyToManyField(related_name="tags", to="core.submission"),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
