# Generated by Django 4.2.4 on 2023-11-24 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("meetings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("1", "1 positive"),
                            ("2", "2 positive under reserve"),
                            ("3a", "3a recessed (not examined)"),
                            ("3b", "3b recessed (examined)"),
                            ("4", "4 negative"),
                            ("5", "5 withdrawn (applicant)"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="vote",
                    ),
                ),
                (
                    "executive_review_required",
                    models.BooleanField(blank=True, null=True),
                ),
                ("text", models.TextField(blank=True, verbose_name="comment")),
                ("is_draft", models.BooleanField(default=False)),
                ("is_final_version", models.BooleanField(default=False)),
                ("is_expired", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(null=True)),
                ("published_at", models.DateTimeField(null=True)),
                ("valid_until", models.DateTimeField(null=True)),
                ("changed_after_voting", models.BooleanField(default=False)),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="core.submissionform",
                    ),
                ),
                (
                    "top",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote",
                        to="meetings.timetableentry",
                    ),
                ),
                (
                    "upgrade_for",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous",
                        to="votes.vote",
                    ),
                ),
            ],
            options={
                "get_latest_by": "published_at",
            },
        ),
    ]
