# Generated by Django 4.2.4 on 2023-11-24 14:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "identifier",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=30
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_downloadable", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "original_file_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "mimetype",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                ("stamp_on_download", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=250)),
                ("version", models.CharField(max_length=250)),
                ("date", models.DateTimeField()),
                ("object_id", models.PositiveIntegerField(null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "doctype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.documenttype",
                    ),
                ),
                (
                    "replaces_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
            ],
        ),
    ]
