# Generated by Django 4.2.4 on 2023-11-24 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0001_initial"),
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionform",
            name="documents",
            field=models.ManyToManyField(
                related_name="submission_forms", to="documents.document"
            ),
        ),
        migrations.AddField(
            model_name="submissionform",
            name="ethics_commissions",
            field=models.ManyToManyField(
                related_name="submission_forms",
                through="core.Investigator",
                to="core.ethicscommission",
            ),
        ),
        migrations.AddField(
            model_name="submissionform",
            name="pdf_document",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submission_form",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="submissionform",
            name="presenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presented_submission_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submissionform",
            name="primary_investigator",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.investigator",
            ),
        ),
        migrations.AddField(
            model_name="submissionform",
            name="sponsor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sponsored_submission_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submissionform",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="core.submission",
            ),
        ),
        migrations.AddField(
            model_name="submissionform",
            name="submitter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_submission_forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="biased_board_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="biased_for_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="current_pending_vote",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_currently_pending_for",
                to="votes.vote",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="current_published_vote",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_currently_published_for",
                to="votes.vote",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="current_submission_form",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_for_submission",
                to="core.submissionform",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="medical_categories",
            field=models.ManyToManyField(
                blank=True, related_name="submissions", to="core.medicalcategory"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="presenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="presented_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="susar_presenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="susar_presented_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participatingcenternonsubject",
            name="ethics_commission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.ethicscommission"
            ),
        ),
        migrations.AddField(
            model_name="participatingcenternonsubject",
            name="submission_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.submissionform"
            ),
        ),
        migrations.AddField(
            model_name="nontesteduseddrug",
            name="submission_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.submissionform"
            ),
        ),
        migrations.AddField(
            model_name="medicalcategory",
            name="users",
            field=models.ManyToManyField(
                related_name="medical_categories", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="submission_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measures",
                to="core.submissionform",
            ),
        ),
        migrations.AddField(
            model_name="investigatoremployee",
            name="investigator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="core.investigator",
            ),
        ),
        migrations.AddField(
            model_name="investigator",
            name="ethics_commission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investigators",
                to="core.ethicscommission",
            ),
        ),
        migrations.AddField(
            model_name="investigator",
            name="submission_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investigators",
                to="core.submissionform",
            ),
        ),
        migrations.AddField(
            model_name="investigator",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="investigations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="foreignparticipatingcenter",
            name="submission_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.submissionform"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.submission"
            ),
        ),
        migrations.AddField(
            model_name="advancedsettings",
            name="default_contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
