# Generated by Django 4.2.4 on 2023-12-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_investigator_submission_form_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mysubmission",
            options={"managed": False},
        ),
    ]
