# Generated by Django 4.2.4 on 2023-12-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_alter_thread_last_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="in_reply_to",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="is_replied_in",
                to="communication.message",
            ),
        ),
    ]
