# Generated by Django 4.2.4 on 2023-11-24 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reversion.views


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("title", models.CharField(max_length=200)),
                ("optimization_task_id", models.TextField(null=True)),
                ("started", models.DateTimeField(null=True)),
                ("ended", models.DateTimeField(null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("deadline", models.DateTimeField(null=True)),
                ("deadline_diplomathesis", models.DateTimeField(null=True)),
                ("deadline_expedited_review", models.DateTimeField(null=True)),
                ("agenda_sent_at", models.DateTimeField(null=True)),
                ("protocol_rendering_started_at", models.DateTimeField(null=True)),
                ("protocol_sent_at", models.DateTimeField(null=True)),
                (
                    "expedited_reviewer_invitation_sent_at",
                    models.DateTimeField(null=True),
                ),
                (
                    "documents_zip",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zip_for_meeting",
                        to="documents.document",
                    ),
                ),
                (
                    "expert_assignment_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol_for_meeting",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
                "db_table": "",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TimetableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("timetable_index", models.IntegerField(null=True)),
                ("duration", models.DurationField()),
                ("is_break", models.BooleanField(default=False)),
                ("optimal_start", models.TimeField(null=True)),
                ("is_open", models.BooleanField(default=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_entries",
                        to="core.submission",
                    ),
                ),
            ],
            bases=(models.Model, reversion.views.RevisionMixin),
        ),
        migrations.AddField(
            model_name="meeting",
            name="submissions",
            field=models.ManyToManyField(
                related_name="meetings",
                through="meetings.TimetableEntry",
                to="core.submission",
            ),
        ),
        migrations.CreateModel(
            name="AssignedMedicalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.medicalcategory",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_categories",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_medical_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(
                fields=("meeting", "timetable_index"),
                name="unique_meeting_timetable_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="timetableentry",
            constraint=models.UniqueConstraint(
                fields=("meeting", "submission"), name="unique_meeting_submission"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignedmedicalcategory",
            constraint=models.UniqueConstraint(
                fields=("category", "meeting"), name="unique_category_meeting"
            ),
        ),
    ]
