# Generated by Django 4.2.4 on 2023-12-10 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_investigator_submission_form_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasksv", "0007_alter_task_managers"),
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meeting",
            options={},
        ),
        migrations.AlterModelTable(
            name="meeting",
            table=None,
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ignored_for_optimization", models.BooleanField(default=False)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="meetings.timetableentry",
                    ),
                ),
                (
                    "medical_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_participations",
                        to="core.medicalcategory",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasksv.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Constraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "weight",
                    models.FloatField(
                        choices=[(1.0, "impossible"), (0.5, "unfavorable")], default=0.5
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constraints",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_constraints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
